const pays = [
  {
    iso: "A1",
    name: "Açores",
    pre: "aux",
    slug: "acores",
    flag: null,
    prefix: 351,
  },
  {
    iso: "AF",
    name: "Afghanistan",
    pre: "en",
    slug: "afghanistan",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/20px-Flag_of_the_Taliban.svg.png",
    prefix: 93,
  },
  {
    iso: "ZA",
    name: "Afrique du sud",
    pre: "en",
    slug: "afrique-du-sud",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/20px-Flag_of_South_Africa.svg.png",
    prefix: 27,
  },
  {
    iso: "AX",
    name: "Îles Aland",
    pre: "aux",
    slug: "iles-aland",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/5/52/Flag_of_%C3%85land.svg/20px-Flag_of_%C3%85land.svg.png",
    prefix: 358,
  },
  {
    iso: "AL",
    name: "Albanie",
    pre: "en",
    slug: "albanie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/20px-Flag_of_Albania.svg.png",
    prefix: 355,
  },
  {
    iso: "DZ",
    name: "Algérie",
    pre: "en",
    slug: "algerie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/20px-Flag_of_Algeria.svg.png",
    prefix: 213,
  },
  {
    iso: "DE",
    name: "Allemagne",
    pre: "en",
    slug: "allemagne",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/20px-Flag_of_Germany.svg.png",
    prefix: 49,
  },
  {
    iso: "AD",
    name: "Andorre",
    pre: "à",
    slug: "andorre",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/20px-Flag_of_Andorra.svg.png",
    prefix: 376,
  },
  {
    iso: "AO",
    name: "Angola",
    pre: "en",
    slug: "angola",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/20px-Flag_of_Angola.svg.png",
    prefix: 244,
  },
  {
    iso: "AI",
    name: "Anguilla",
    pre: "à",
    slug: "anguilla",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Anguilla.svg/20px-Flag_of_Anguilla.svg.png",
    prefix: 1264,
  },
  {
    iso: "AQ",
    name: "Antarctique",
    pre: "en",
    slug: "antarctique",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Proposed_flag_of_Antarctica_%28Graham_Bartram%29.svg/20px-Proposed_flag_of_Antarctica_%28Graham_Bartram%29.svg.png",
    prefix: 672,
  },
  {
    iso: "AG",
    name: "Antigua et Barbuda",
    pre: "à",
    slug: "antigua-et-barbuda",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/20px-Flag_of_Antigua_and_Barbuda.svg.png",
    prefix: 1268,
  },
  {
    iso: "AN",
    name: "Antilles Néerlandaises",
    pre: "aux",
    slug: "antilles-neerlandaises",
  },
  {
    iso: "SA",
    name: "Arabie Saoudite",
    pre: "en",
    slug: "arabie-saoudite",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/20px-Flag_of_Saudi_Arabia.svg.png",
    prefix: 966,
  },
  {
    iso: "AR",
    name: "Argentine",
    pre: "en",
    slug: "argentine",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/20px-Flag_of_Argentina.svg.png",
    prefix: 54,
  },
  {
    iso: "AM",
    name: "Arménie",
    pre: "en",
    slug: "armenie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/20px-Flag_of_Armenia.svg.png",
    prefix: 374,
  },
  {
    iso: "AW",
    name: "Aruba",
    pre: "à",
    slug: "aruba",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Aruba.svg/20px-Flag_of_Aruba.svg.png",
    prefix: 297,
  },
  {
    iso: "AU",
    name: "Australie",
    pre: "en",
    slug: "australie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/20px-Flag_of_Australia.svg.png",
    prefix: 61,
  },
  {
    iso: "AT",
    name: "Autriche",
    pre: "en",
    slug: "autriche",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/20px-Flag_of_Austria.svg.png",
    prefix: 43,
  },
  {
    iso: "AZ",
    name: "Azerbaïdjan",
    pre: "en",
    slug: "azerbaidjan",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/20px-Flag_of_Azerbaijan.svg.png",
    prefix: 994,
  },
  {
    iso: "BS",
    name: "Bahamas",
    pre: "aux",
    slug: "bahamas",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/20px-Flag_of_the_Bahamas.svg.png",
    prefix: 1242,
  },
  {
    iso: "BH",
    name: "Bahrein",
    pre: "à",
    slug: "bahrein",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/20px-Flag_of_Bahrain.svg.png",
    prefix: 973,
  },
  { iso: "B1", name: "Baléares", pre: "aux", slug: "baleares" },
  {
    iso: "BD",
    name: "Bangladesh",
    pre: "au",
    slug: "bangladesh",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/20px-Flag_of_Bangladesh.svg.png",
    prefix: 880,
  },
  {
    iso: "BB",
    name: "Barbade",
    pre: "à la",
    slug: "barbade",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/20px-Flag_of_Barbados.svg.png",
    prefix: 1246,
  },
  {
    iso: "BY",
    name: "Biélorussie",
    pre: "en",
    slug: "bielorussie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/20px-Flag_of_Belarus.svg.png",
    prefix: 375,
  },
  {
    iso: "BE",
    name: "Belgique",
    pre: "en",
    slug: "belgique",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/20px-Flag_of_Belgium_%28civil%29.svg.png",
    prefix: 32,
  },
  {
    iso: "BZ",
    name: "Belize",
    pre: "au",
    slug: "belize",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/20px-Flag_of_Belize.svg.png",
    prefix: 501,
  },
  {
    iso: "BJ",
    name: "Bénin",
    pre: "au",
    slug: "benin",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/20px-Flag_of_Benin.svg.png",
    prefix: 229,
  },
  {
    iso: "BM",
    name: "Bermudes",
    pre: "aux",
    slug: "bermudes",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bermuda.svg/20px-Flag_of_Bermuda.svg.png",
    prefix: 1441,
  },
  {
    iso: "BT",
    name: "Bhoutan",
    pre: "au",
    slug: "bhoutan",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/20px-Flag_of_Bhutan.svg.png",
    prefix: 975,
  },
  {
    iso: "BO",
    name: "Bolivie",
    pre: "en",
    slug: "bolivie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bandera_de_Bolivia_%28Estado%29.svg/20px-Bandera_de_Bolivia_%28Estado%29.svg.png",
    prefix: 591,
  },
  {
    iso: "BA",
    name: "Bosnie Herzegovine",
    pre: "en",
    slug: "bosnie-herzegovine",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/20px-Flag_of_Bosnia_and_Herzegovina.svg.png",
    prefix: 387,
  },
  {
    iso: "BW",
    name: "Botswana",
    pre: "au",
    slug: "botswana",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/20px-Flag_of_Botswana.svg.png",
    prefix: 267,
  },
  {
    iso: "BV",
    name: "Île Bouvet",
    pre: "à l'",
    slug: "ile-bouvet",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/20px-Flag_of_Norway.svg.png",
    prefix: 47,
  },
  {
    iso: "BR",
    name: "Brésil",
    pre: "au",
    slug: "bresil",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/20px-Flag_of_Brazil.svg.png",
    prefix: 55,
  },
  {
    iso: "BN",
    name: "Brunei Darussalam",
    pre: "au",
    slug: "brunei-darussalam",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/20px-Flag_of_Brunei.svg.png",
    prefix: 673,
  },
  {
    iso: "BG",
    name: "Bulgarie",
    pre: "en",
    slug: "bulgarie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/20px-Flag_of_Bulgaria.svg.png",
    prefix: 359,
  },
  {
    iso: "BF",
    name: "Burkina Faso",
    pre: "au",
    slug: "burkina-faso",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/20px-Flag_of_Burkina_Faso.svg.png",
    prefix: 226,
  },
  {
    iso: "BI",
    name: "Burundi",
    pre: "au",
    slug: "burundi",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/20px-Flag_of_Burundi.svg.png",
    prefix: 257,
  },
  {
    iso: "KY",
    name: "Îles Caïmans",
    pre: "aux",
    slug: "iles-caimans",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_the_Cayman_Islands.svg/20px-Flag_of_the_Cayman_Islands.svg.png",
    prefix: 1345,
  },
  {
    iso: "KH",
    name: "Cambodge",
    pre: "au",
    slug: "cambodge",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/20px-Flag_of_Cambodia.svg.png",
    prefix: 855,
  },
  {
    iso: "CM",
    name: "Cameroun",
    pre: "au",
    slug: "cameroun",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/20px-Flag_of_Cameroon.svg.png",
    prefix: 237,
  },
  {
    iso: "CA",
    name: "Canada",
    pre: "au",
    slug: "canada",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada.svg/20px-Flag_of_Canada.svg.png",
    prefix: 1,
  },
  { iso: "IC", name: "Canaries", pre: "aux", slug: "canaries" },
  {
    iso: "CV",
    name: "Cap Vert",
    pre: "au",
    slug: "cap-vert",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/20px-Flag_of_Cape_Verde.svg.png",
    prefix: 238,
  },
  {
    iso: "CF",
    name: "Centrafrique",
    pre: "en",
    slug: "centrafrique",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/20px-Flag_of_the_Central_African_Republic.svg.png",
    prefix: 236,
  },
  {
    iso: "EA",
    name: "Ceuta et Melilla",
    pre: "à",
    slug: "ceuta-et-melilla",
    flag: null,
    prefix: 34,
  },
  {
    iso: "CL",
    name: "Chili",
    pre: "au",
    slug: "chili",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/20px-Flag_of_Chile.svg.png",
    prefix: 56,
  },
  {
    iso: "CN",
    name: "Chine",
    pre: "en",
    slug: "chine",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/20px-Flag_of_the_People%27s_Republic_of_China.svg.png",
    prefix: 86,
  },
  { iso: "CX", name: "Île Christmas", pre: "à l'", slug: "ile-christmas" },
  {
    iso: "CY",
    name: "Chypre",
    pre: "en",
    slug: "chypre",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/20px-Flag_of_Cyprus.svg.png",
    prefix: 357,
  },
  {
    iso: "CC",
    name: "Îles Cocos, Keeling",
    pre: "aux",
    slug: "iles-cocos-keeling",
    flag: null,
    prefix: 61,
  },
  {
    iso: "CO",
    name: "Colombie",
    pre: "en",
    slug: "colombie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/20px-Flag_of_Colombia.svg.png",
    prefix: 57,
  },
  {
    iso: "KM",
    name: "Comores",
    pre: "aux",
    slug: "comores",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/20px-Flag_of_the_Comoros.svg.png",
    prefix: 269,
  },
  {
    iso: "CG",
    name: "Congo",
    pre: "au",
    slug: "congo",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/20px-Flag_of_the_Republic_of_the_Congo.svg.png",
    prefix: 242,
  },
  {
    iso: "CD",
    name: "République Démocratique du Congo",
    pre: "à la",
    slug: "republique-democratique-du-congo",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/20px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png",
    prefix: 243,
  },
  {
    iso: "CK",
    name: "Îles Cook",
    pre: "aux",
    slug: "iles-cook",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_the_Cook_Islands.svg/20px-Flag_of_the_Cook_Islands.svg.png",
    prefix: 682,
  },
  {
    iso: "KR",
    name: "Corée du Sud",
    pre: "en",
    slug: "coree-du-sud",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/20px-Flag_of_South_Korea.svg.png",
    prefix: 82,
  },
  {
    iso: "KP",
    name: "Corée du Nord",
    pre: "en",
    slug: "coree-du-nord",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/20px-Flag_of_North_Korea.svg.png",
    prefix: 850,
  },
  {
    iso: "KL",
    name: "Corse",
    pre: "en",
    slug: "corse",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg/20px-Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg.png",
    prefix: 33,
  },
  {
    iso: "CR",
    name: "Costa Rica",
    pre: "au",
    slug: "costa-rica",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/20px-Flag_of_Costa_Rica.svg.png",
    prefix: 506,
  },
  {
    iso: "CI",
    name: "Côte d'Ivoire",
    pre: "en",
    slug: "cote-divoire",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg/20px-Flag_of_C%C3%B4te_d%27Ivoire.svg.png",
    prefix: 225,
  },
  {
    iso: "C1",
    name: "Crète",
    pre: "en",
    slug: "crete",
    flag: null,
    prefix: 30,
  },
  {
    iso: "HR",
    name: "Croatie",
    pre: "en",
    slug: "croatie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/20px-Flag_of_Croatia.svg.png",
    prefix: 385,
  },
  {
    iso: "1F",
    name: "Croisière Fluviale",
    pre: "en",
    slug: "croisiere-fluviale",
    flag: null,
    prefix: null,
  },
  {
    iso: "1M",
    name: "Croisière Maritime ",
    pre: "en",
    slug: "croisiere-maritime",
    flag: null,
    prefix: null,
  },
  {
    iso: "CU",
    name: "Cuba",
    pre: "au",
    slug: "cuba",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/20px-Flag_of_Cuba.svg.png",
    prefix: 53,
  },
  {
    iso: "CW",
    name: "Curaçao ",
    pre: "à",
    slug: "curacao",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_Cura%C3%A7ao.svg/20px-Flag_of_Cura%C3%A7ao.svg.png",
    prefix: 599,
  },
  {
    iso: "DK",
    name: "Danemark",
    pre: "au",
    slug: "danemark",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/20px-Flag_of_Denmark.svg.png",
    prefix: 45,
  },
  {
    iso: "DJ",
    name: "Djibouti",
    pre: "à",
    slug: "djibouti",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/20px-Flag_of_Djibouti.svg.png",
    prefix: 253,
  },
  {
    iso: "DO",
    name: "République Dominicaine",
    pre: "en",
    slug: "republique-dominicaine",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/20px-Flag_of_the_Dominican_Republic.svg.png",
    prefix: 1809,
  },
  {
    iso: "DM",
    name: "Dominique",
    pre: "à la",
    slug: "dominique",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/20px-Flag_of_Dominica.svg.png",
    prefix: 1767,
  },
  {
    iso: "E1",
    name: "Ecosse",
    pre: "en",
    slug: "ecosse",
    flag: null,
    prefix: 44,
  },
  {
    iso: "EG",
    name: "Egypte",
    pre: "en",
    slug: "egypte",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/20px-Flag_of_Egypt.svg.png",
    prefix: 20,
  },
  {
    iso: "SV",
    name: "El Salvador",
    pre: "à",
    slug: "el-salvador",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/20px-Flag_of_El_Salvador.svg.png",
    prefix: 503,
  },
  {
    iso: "AE",
    name: "Emirats Arabes Unis",
    pre: "aux",
    slug: "emirats-arabes-unis",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/20px-Flag_of_the_United_Arab_Emirates.svg.png",
    prefix: 971,
  },
  {
    iso: "EC",
    name: "Equateur",
    pre: "en",
    slug: "equateur",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/20px-Flag_of_Ecuador.svg.png",
    prefix: 593,
  },
  {
    iso: "ER",
    name: "Erythrée",
    pre: "en",
    slug: "erythree",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/20px-Flag_of_Eritrea.svg.png",
    prefix: 291,
  },
  {
    iso: "ES",
    name: "Espagne",
    pre: "en",
    slug: "espagne",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/20px-Flag_of_Spain.svg.png",
    prefix: 34,
  },
  {
    iso: "EE",
    name: "Estonie",
    pre: "en",
    slug: "estonie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/20px-Flag_of_Estonia.svg.png",
    prefix: 372,
  },
  {
    iso: "US",
    name: "Etats Unis",
    pre: "aux",
    slug: "etats-unis",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/20px-Flag_of_the_United_States.svg.png",
    prefix: 1,
  },
  {
    iso: "ET",
    name: "Ethiopie",
    pre: "en",
    slug: "ethiopie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/20px-Flag_of_Ethiopia.svg.png",
    prefix: 251,
  },
  {
    iso: "E2",
    name: "Expéditions Africaines",
    pre: "en",
    slug: "expeditions-africaines",
    flag: null,
    prefix: null,
  },
  {
    iso: "E3",
    name: "Expéditions Sud Américaines",
    pre: "en",
    slug: "expeditions-sud-americaines",
    flag: null,
    prefix: null,
  },
  {
    iso: "FK",
    name: "Falkland, Malouines",
    pre: "aux",
    slug: "falkland-malouines",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_Falkland_Islands.svg/20px-Flag_of_the_Falkland_Islands.svg.png",
    prefix: 500,
  },
  {
    iso: "FO",
    name: "Îles Feroe",
    pre: "aux",
    slug: "iles-feroe",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Flag_of_the_Faroe_Islands.svg/20px-Flag_of_the_Faroe_Islands.svg.png",
    prefix: 298,
  },
  {
    iso: "FJ",
    name: "Fidji",
    pre: "à",
    slug: "fidji",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/20px-Flag_of_Fiji.svg.png",
    prefix: 679,
  },
  {
    iso: "FI",
    name: "Finlande",
    pre: "en",
    slug: "finlande",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/20px-Flag_of_Finland.svg.png",
    prefix: 358,
  },
  {
    iso: "FR",
    name: "France",
    pre: "en",
    slug: "france",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg/20px-Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg.png",
    prefix: 33,
  },
  {
    iso: "GA",
    name: "Gabon",
    pre: "au",
    slug: "gabon",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/20px-Flag_of_Gabon.svg.png",
    prefix: 241,
  },
  {
    iso: "GM",
    name: "Gambie",
    pre: "en",
    slug: "gambie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/20px-Flag_of_The_Gambia.svg.png",
    prefix: 220,
  },
  {
    iso: "GE",
    name: "Géorgie",
    pre: "en",
    slug: "georgie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/20px-Flag_of_Georgia.svg.png",
    prefix: 995,
  },
  {
    iso: "GS",
    name: "Géorgie du Sud et Îles Sandwich",
    pre: "en",
    slug: "georgie-du-sud-et-iles-sandwich",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg/20px-Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg.png",
    prefix: 500,
  },
  {
    iso: "GH",
    name: "Ghana",
    pre: "au",
    slug: "ghana",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/20px-Flag_of_Ghana.svg.png",
    prefix: 233,
  },
  {
    iso: "GI",
    name: "Gibraltar",
    pre: "à",
    slug: "gibraltar",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/02/Flag_of_Gibraltar.svg/20px-Flag_of_Gibraltar.svg.png",
    prefix: 350,
  },
  {
    iso: "GR",
    name: "Grèce",
    pre: "en",
    slug: "grece",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/20px-Flag_of_Greece.svg.png",
    prefix: 30,
  },
  {
    iso: "GD",
    name: "Grenade",
    pre: "à la",
    slug: "grenade",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/20px-Flag_of_Grenada.svg.png",
    prefix: 1473,
  },
  {
    iso: "GL",
    name: "Groenland",
    pre: "au",
    slug: "groenland",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/20px-Flag_of_Greenland.svg.png",
    prefix: 299,
  },
  {
    iso: "GP",
    name: "Guadeloupe",
    pre: "en",
    slug: "guadeloupe",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/20px-Flag_of_France.svg.png",
    prefix: 590,
  },
  {
    iso: "GU",
    name: "Guam",
    pre: "à",
    slug: "guam",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/20px-Flag_of_Guam.svg.png",
    prefix: 1671,
  },
  {
    iso: "GT",
    name: "Guatemala",
    pre: "au",
    slug: "guatemala",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/20px-Flag_of_Guatemala.svg.png",
    prefix: 502,
  },
  {
    iso: "GG",
    name: "Guernesey",
    pre: "à",
    slug: "guernesey",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Guernsey.svg/20px-Flag_of_Guernsey.svg.png",
    prefix: 44,
  },
  {
    iso: "GN",
    name: "Guinée",
    pre: "en",
    slug: "guinee",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/20px-Flag_of_Guinea.svg.png",
    prefix: 224,
  },
  {
    iso: "GQ",
    name: "Guinée Equatoriale",
    pre: "en",
    slug: "guinee-equatoriale",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/20px-Flag_of_Equatorial_Guinea.svg.png",
    prefix: 240,
  },
  {
    iso: "GW",
    name: "Guinée Bissau",
    pre: "en",
    slug: "guinee-bissau",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/20px-Flag_of_Guinea-Bissau.svg.png",
    prefix: 245,
  },
  {
    iso: "GY",
    name: "Guyana",
    pre: "à",
    slug: "guyana",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/20px-Flag_of_Guyana.svg.png",
    prefix: 592,
  },
  {
    iso: "GF",
    name: "Guyane Française",
    pre: "en",
    slug: "guyane-francaise",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/20px-Flag_of_France.svg.png",
    prefix: 594,
  },
  {
    iso: "HT",
    name: "Haïti",
    pre: "à",
    slug: "haiti",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/20px-Flag_of_Haiti.svg.png",
    prefix: 509,
  },
  { iso: "H1", name: "Hawaï", pre: "à", slug: "hawai", flag: null, prefix: 1 },
  {
    iso: "HM",
    name: "Îles Heard et Mcdonald",
    pre: "aux",
    slug: "iles-heard-et-mcdonald",
    flag: null,
    prefix: null,
  },
  {
    iso: "HN",
    name: "Honduras",
    pre: "au",
    slug: "honduras",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Flag_of_Honduras_%281949%E2%80%932022%29.svg/20px-Flag_of_Honduras_%281949%E2%80%932022%29.svg.png",
    prefix: 504,
  },
  {
    iso: "HK",
    name: "Hong Kong",
    pre: "à",
    slug: "hong-kong",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/20px-Flag_of_Hong_Kong.svg.png",
    prefix: 852,
  },
  {
    iso: "HU",
    name: "Hongrie",
    pre: "en",
    slug: "hongrie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/20px-Flag_of_Hungary.svg.png",
    prefix: 36,
  },
  {
    iso: "IM",
    name: "Île de Man",
    pre: "à l'",
    slug: "ile-de-man",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Flag_of_the_Isle_of_Mann.svg/20px-Flag_of_the_Isle_of_Mann.svg.png",
    prefix: 44,
  },
  {
    iso: "1I",
    name: "Îles Grecques",
    pre: "",
    slug: "iles-grecques",
    flag: null,
    prefix: null,
  },
  {
    iso: "UM",
    name: "Îles Mineures Eloignées des Etats Unis",
    pre: "aux",
    slug: "iles-mineures-eloignees-des-etats-unis",
    flag: null,
    prefix: null,
  },
  {
    iso: "VG",
    name: "Îles Vierges Britanniques",
    pre: "aux",
    slug: "iles-vierges-britanniques",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_the_British_Virgin_Islands.svg/20px-Flag_of_the_British_Virgin_Islands.svg.png",
    prefix: 1284,
  },
  {
    iso: "VI",
    name: "Îles Vierges des Etats Unis",
    pre: "aux",
    slug: "iles-vierges-des-etats-unis",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_the_United_States_Virgin_Islands.svg/20px-Flag_of_the_United_States_Virgin_Islands.svg.png",
    prefix: 1340,
  },
  {
    iso: "IN",
    name: "Inde",
    pre: "en",
    slug: "inde",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/20px-Flag_of_India.svg.png",
    prefix: 91,
  },
  {
    iso: "ID",
    name: "Indonésie",
    pre: "en",
    slug: "indonesie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/20px-Flag_of_Indonesia.svg.png",
    prefix: 62,
  },
  {
    iso: "IR",
    name: "Iran",
    pre: "en",
    slug: "iran",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/20px-Flag_of_Iran.svg.png",
    prefix: 98,
  },
  {
    iso: "IQ",
    name: "Iraq",
    pre: "en",
    slug: "iraq",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/20px-Flag_of_Iraq.svg.png",
    prefix: 964,
  },
  {
    iso: "IE",
    name: "Irlande",
    pre: "en",
    slug: "irlande",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/20px-Flag_of_Ireland.svg.png",
    prefix: 353,
  },
  {
    iso: "I1",
    name: "Irlande du Nord",
    pre: "en",
    slug: "irlande-du-nord",
    flag: null,
    prefix: 44,
  },
  {
    iso: "IS",
    name: "Islande",
    pre: "en",
    slug: "islande",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/20px-Flag_of_Iceland.svg.png",
    prefix: 354,
  },
  {
    iso: "IL",
    name: "Israel",
    pre: "en",
    slug: "israel",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/20px-Flag_of_Israel.svg.png",
    prefix: 972,
  },
  {
    iso: "IT",
    name: "Italie",
    pre: "en",
    slug: "italie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/20px-Flag_of_Italy.svg.png",
    prefix: 39,
  },
  {
    iso: "JM",
    name: "Jamaïque",
    pre: "en",
    slug: "jamaique",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/20px-Flag_of_Jamaica.svg.png",
    prefix: 1876,
  },
  {
    iso: "JP",
    name: "Japon",
    pre: "au",
    slug: "japon",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/20px-Flag_of_Japan.svg.png",
    prefix: 81,
  },
  {
    iso: "JE",
    name: "Jersey",
    pre: "à",
    slug: "jersey",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Flag_of_Jersey.svg/20px-Flag_of_Jersey.svg.png",
    prefix: 44,
  },
  {
    iso: "JO",
    name: "Jordanie",
    pre: "en",
    slug: "jordanie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/20px-Flag_of_Jordan.svg.png",
    prefix: 962,
  },
  {
    iso: "KZ",
    name: "Kazakhstan",
    pre: "au",
    slug: "kazakhstan",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/20px-Flag_of_Kazakhstan.svg.png",
    prefix: 7,
  },
  {
    iso: "KE",
    name: "Kenya",
    pre: "au",
    slug: "kenya",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/20px-Flag_of_Kenya.svg.png",
    prefix: 254,
  },
  {
    iso: "KG",
    name: "Kirghizistan",
    pre: "au",
    slug: "kirghizistan",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/20px-Flag_of_Kyrgyzstan.svg.png",
    prefix: 996,
  },
  {
    iso: "KI",
    name: "Kiribati",
    pre: "à",
    slug: "kiribati",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/20px-Flag_of_Kiribati.svg.png",
    prefix: 686,
  },
  {
    iso: "KW",
    name: "Koweit",
    pre: "au",
    slug: "koweit",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/20px-Flag_of_Kuwait.svg.png",
    prefix: 965,
  },
  {
    iso: "LA",
    name: "Laos",
    pre: "au",
    slug: "laos",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/20px-Flag_of_Laos.svg.png",
    prefix: 856,
  },
  {
    iso: "LS",
    name: "Lesotho",
    pre: "au",
    slug: "lesotho",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/20px-Flag_of_Lesotho.svg.png",
    prefix: 266,
  },
  {
    iso: "LV",
    name: "Lettonie",
    pre: "en",
    slug: "lettonie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/20px-Flag_of_Latvia.svg.png",
    prefix: 371,
  },
  {
    iso: "LB",
    name: "Liban",
    pre: "au",
    slug: "liban",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/20px-Flag_of_Lebanon.svg.png",
    prefix: 961,
  },
  {
    iso: "LR",
    name: "Libéria",
    pre: "au",
    slug: "liberia",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/20px-Flag_of_Liberia.svg.png",
    prefix: 231,
  },
  {
    iso: "LY",
    name: "Libye",
    pre: "en",
    slug: "libye",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/20px-Flag_of_Libya.svg.png",
    prefix: 218,
  },
  {
    iso: "LI",
    name: "Liechtenstein",
    pre: "au",
    slug: "liechtenstein",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/20px-Flag_of_Liechtenstein.svg.png",
    prefix: 423,
  },
  {
    iso: "LT",
    name: "Lituanie",
    pre: "en",
    slug: "lituanie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/20px-Flag_of_Lithuania.svg.png",
    prefix: 370,
  },
  {
    iso: "LU",
    name: "Luxembourg",
    pre: "au",
    slug: "luxembourg",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/20px-Flag_of_Luxembourg.svg.png",
    prefix: 352,
  },
  {
    iso: "MO",
    name: "Macao",
    pre: "à",
    slug: "macao",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/6/63/Flag_of_Macau.svg/20px-Flag_of_Macau.svg.png",
    prefix: 853,
  },
  {
    iso: "MK",
    name: "Macedoine",
    pre: "en",
    slug: "macedoine",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_North_Macedonia.svg/20px-Flag_of_North_Macedonia.svg.png",
    prefix: 389,
  },
  {
    iso: "MG",
    name: "Madagascar",
    pre: "à",
    slug: "madagascar",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/20px-Flag_of_Madagascar.svg.png",
    prefix: 261,
  },
  { iso: "M1", name: "Madère", pre: "à", slug: "madere" },
  {
    iso: "MY",
    name: "Malaisie",
    pre: "en",
    slug: "malaisie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/20px-Flag_of_Malaysia.svg.png",
    prefix: 60,
  },
  {
    iso: "MW",
    name: "Malawi",
    pre: "au",
    slug: "malawi",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/20px-Flag_of_Malawi.svg.png",
    prefix: 265,
  },
  {
    iso: "MV",
    name: "Maldives",
    pre: "aux",
    slug: "maldives",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/20px-Flag_of_Maldives.svg.png",
    prefix: 960,
  },
  {
    iso: "ML",
    name: "Mali",
    pre: "au",
    slug: "mali",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/20px-Flag_of_Mali.svg.png",
    prefix: 223,
  },
  {
    iso: "MT",
    name: "Malte",
    pre: "à",
    slug: "malte",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/20px-Flag_of_Malta.svg.png",
    prefix: 356,
  },
  {
    iso: "MP",
    name: "Îles Mariannes du Nord",
    pre: "aux",
    slug: "iles-mariannes-du-nord",
  },
  {
    iso: "M3",
    name: "Marie Galante",
    pre: "à",
    slug: "marie-galante",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_the_Northern_Mariana_Islands.svg/20px-Flag_of_the_Northern_Mariana_Islands.svg.png",
    prefix: 1670,
  },
  {
    iso: "MA",
    name: "Maroc",
    pre: "au",
    slug: "maroc",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/20px-Flag_of_Morocco.svg.png",
    prefix: 212,
  },
  {
    iso: "MH",
    name: "Îles Marshall",
    pre: "aux",
    slug: "iles-marshall",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flag_of_the_Marshall_Islands.svg/20px-Flag_of_the_Marshall_Islands.svg.png",
    prefix: 692,
  },
  {
    iso: "MQ",
    name: "Martinique",
    pre: "en",
    slug: "martinique",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/20px-Flag_of_France.svg.png",
    prefix: 596,
  },
  {
    iso: "MU",
    name: "Maurice",
    pre: "à",
    slug: "maurice",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/20px-Flag_of_Mauritius.svg.png",
    prefix: 230,
  },
  {
    iso: "MR",
    name: "Mauritanie",
    pre: "en",
    slug: "mauritanie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/20px-Flag_of_Mauritania.svg.png",
    prefix: 222,
  },
  {
    iso: "YT",
    name: "Mayotte",
    pre: "à",
    slug: "mayotte",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/20px-Flag_of_France.svg.png",
    prefix: 262,
  },
  { iso: "M2", name: "Méditerrannée", pre: "en", slug: "mediterrannee" },
  {
    iso: "MX",
    name: "Mexique",
    pre: "au",
    slug: "mexique",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/20px-Flag_of_Mexico.svg.png",
    prefix: 52,
  },
  {
    iso: "FM",
    name: "Micronésie",
    pre: "en",
    slug: "micronesie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg/20px-Flag_of_the_Federated_States_of_Micronesia.svg.png",
    prefix: 691,
  },
  {
    iso: "MD",
    name: "Moldavie",
    pre: "en",
    slug: "moldavie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/20px-Flag_of_Moldova.svg.png",
    prefix: 373,
  },
  {
    iso: "MC",
    name: "Monaco",
    pre: "à",
    slug: "monaco",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/20px-Flag_of_Monaco.svg.png",
    prefix: 377,
  },
  {
    iso: "MN",
    name: "Mongolie",
    pre: "en",
    slug: "mongolie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/20px-Flag_of_Mongolia.svg.png",
    prefix: 976,
  },
  {
    iso: "ME",
    name: "Montenegro",
    pre: "au",
    slug: "montenegro",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/20px-Flag_of_Montenegro.svg.png",
    prefix: 382,
  },
  {
    iso: "MS",
    name: "Montserrat",
    pre: "à",
    slug: "montserrat",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Montserrat.svg/20px-Flag_of_Montserrat.svg.png",
    prefix: 1664,
  },
  {
    iso: "MZ",
    name: "Mozambique",
    pre: "en",
    slug: "mozambique",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/20px-Flag_of_Mozambique.svg.png",
    prefix: 258,
  },
  {
    iso: "MM",
    name: "Myanmar",
    pre: "au",
    slug: "myanmar",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/20px-Flag_of_Myanmar.svg.png",
    prefix: 95,
  },
  {
    iso: "NA",
    name: "Namibie",
    pre: "en",
    slug: "namibie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/20px-Flag_of_Namibia.svg.png",
    prefix: 264,
  },
  {
    iso: "NR",
    name: "Nauru",
    pre: "à",
    slug: "nauru",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Nauru.svg/20px-Flag_of_Nauru.svg.png",
    prefix: 674,
  },
  {
    iso: "NP",
    name: "Nepal",
    pre: "au",
    slug: "nepal",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/15px-Flag_of_Nepal.svg.png",
    prefix: 977,
  },
  {
    iso: "NI",
    name: "Nicaragua",
    pre: "au",
    slug: "nicaragua",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/20px-Flag_of_Nicaragua.svg.png",
    prefix: 505,
  },
  {
    iso: "NE",
    name: "Niger",
    pre: "au",
    slug: "niger",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/20px-Flag_of_Niger.svg.png",
    prefix: 227,
  },
  {
    iso: "NG",
    name: "Nigeria",
    pre: "au",
    slug: "nigeria",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/20px-Flag_of_Nigeria.svg.png",
    prefix: 234,
  },
  {
    iso: "NU",
    name: "Niue",
    pre: "à",
    slug: "niue",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Niue.svg/20px-Flag_of_Niue.svg.png",
    prefix: 683,
  },
  {
    iso: "NF",
    name: "Île Norfolk",
    pre: "à l'",
    slug: "ile-norfolk",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Norfolk_Island.svg/20px-Flag_of_Norfolk_Island.svg.png",
    prefix: 6723,
  },
  {
    iso: "NO",
    name: "Norvège",
    pre: "en",
    slug: "norvege",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/20px-Flag_of_Norway.svg.png",
    prefix: 47,
  },
  {
    iso: "NC",
    name: "Nouvelle Calédonie",
    pre: "en",
    slug: "nouvelle-caledonie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flags_of_New_Caledonia.svg/20px-Flags_of_New_Caledonia.svg.png",
    prefix: 687,
  },
  {
    iso: "NZ",
    name: "Nouvelle Zélande",
    pre: "en",
    slug: "nouvelle-zelande",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/20px-Flag_of_New_Zealand.svg.png",
    prefix: 64,
  },
  {
    iso: "IO",
    name: "Territoire Britannique de L'Ocean Indien",
    pre: "au",
    slug: "territoire-britannique-de-locean-indien",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg/20px-Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg.png",
    prefix: 246,
  },
  {
    iso: "OM",
    name: "Oman",
    pre: "à",
    slug: "oman",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/20px-Flag_of_Oman.svg.png",
    prefix: 968,
  },
  {
    iso: "UG",
    name: "Ouganda",
    pre: "en",
    slug: "ouganda",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/20px-Flag_of_Uganda.svg.png",
    prefix: 256,
  },
  {
    iso: "UZ",
    name: "Ouzbekistan",
    pre: "en",
    slug: "ouzbekistan",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/20px-Flag_of_Uzbekistan.svg.png",
    prefix: 998,
  },
  {
    iso: "PK",
    name: "Pakistan",
    pre: "au",
    slug: "pakistan",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/20px-Flag_of_Pakistan.svg.png",
    prefix: 92,
  },
  {
    iso: "PW",
    name: "Palaos",
    pre: "à",
    slug: "palaos",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Palau.svg/20px-Flag_of_Palau.svg.png",
    prefix: 680,
  },
  {
    iso: "PS",
    name: "Palestine",
    pre: "au",
    slug: "palestine",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/20px-Flag_of_Palestine.svg.png",
    prefix: 970,
  },
  {
    iso: "PA",
    name: "Panama",
    pre: "au",
    slug: "panama",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/20px-Flag_of_Panama.svg.png",
    prefix: 507,
  },
  {
    iso: "PG",
    name: "Papouasie Nouvelle Guinée",
    pre: "en",
    slug: "papouasie-nouvelle-guinee",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/20px-Flag_of_Papua_New_Guinea.svg.png",
    prefix: 675,
  },
  {
    iso: "PY",
    name: "Paraguay",
    pre: "au",
    slug: "paraguay",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/20px-Flag_of_Paraguay.svg.png",
    prefix: 595,
  },
  {
    iso: "NL",
    name: "Pays Bas",
    pre: "au",
    slug: "pays-bas",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/20px-Flag_of_the_Netherlands.svg.png",
    prefix: 31,
  },
  {
    iso: "PE",
    name: "Perou",
    pre: "au",
    slug: "perou",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/20px-Flag_of_Peru.svg.png",
    prefix: 51,
  },
  {
    iso: "PH",
    name: "Philippines",
    pre: "aux",
    slug: "philippines",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/20px-Flag_of_the_Philippines.svg.png",
    prefix: 63,
  },
  {
    iso: "PN",
    name: "Pitcairn",
    pre: "à",
    slug: "pitcairn",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_the_Pitcairn_Islands.svg/20px-Flag_of_the_Pitcairn_Islands.svg.png",
    prefix: 64,
  },
  {
    iso: "PL",
    name: "Pologne",
    pre: "en",
    slug: "pologne",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/20px-Flag_of_Poland.svg.png",
    prefix: 48,
  },
  {
    iso: "PF",
    name: "Polynésie Francaise",
    pre: "en",
    slug: "polynesie-francaise",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/db/Flag_of_French_Polynesia.svg/20px-Flag_of_French_Polynesia.svg.png",
    prefix: 689,
  },
  {
    iso: "PR",
    name: "Porto Rico",
    pre: "à",
    slug: "porto-rico",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/20px-Flag_of_Puerto_Rico.svg.png",
    prefix: 1787,
  },
  {
    iso: "PT",
    name: "Portugal",
    pre: "au",
    slug: "portugal",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/20px-Flag_of_Portugal.svg.png",
    prefix: 351,
  },
  {
    iso: "QA",
    name: "Qatar",
    pre: "au",
    slug: "qatar",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/20px-Flag_of_Qatar.svg.png",
    prefix: 974,
  },
  {
    iso: "RE",
    name: "Réunion",
    pre: "à la",
    slug: "reunion",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/db/ReunionRadiantVolcanoFlag.png/20px-ReunionRadiantVolcanoFlag.png",
    prefix: 262,
  },
  {
    iso: "RO",
    name: "Roumanie",
    pre: "en",
    slug: "roumanie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/20px-Flag_of_Romania.svg.png",
    prefix: 40,
  },
  {
    iso: "GB",
    name: "Royaume Uni",
    pre: "au",
    slug: "royaume-uni",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg/20px-Flag_of_the_United_Kingdom_%283-5%29.svg.png",
    prefix: 44,
  },
  {
    iso: "RU",
    name: "Russie",
    pre: "en",
    slug: "russie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/20px-Flag_of_Russia.svg.png",
    prefix: 7,
  },
  {
    iso: "RW",
    name: "Rwanda",
    pre: "au",
    slug: "rwanda",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/20px-Flag_of_Rwanda.svg.png",
    prefix: 250,
  },
  {
    iso: "EH",
    name: "Sahara Occidental",
    pre: "au",
    slug: "sahara-occidental",
  },
  {
    iso: "BL",
    name: "Saint Barthelemy",
    pre: "à",
    slug: "saint-barthelemy",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/20px-Flag_of_France.svg.png",
    prefix: 590,
  },
  {
    iso: "MF",
    name: "Saint Martin (France)",
    pre: "à",
    slug: "saint-martin-france",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/20px-Flag_of_France.svg.png",
    prefix: 590,
  },
  {
    iso: "KN",
    name: "Saint Kitts et Nevis",
    pre: "à",
    slug: "saint-kitts-et-nevis",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg/20px-Flag_of_Saint_Kitts_and_Nevis.svg.png",
    prefix: 1869,
  },
  {
    iso: "SM",
    name: "Saint Marin",
    pre: "à",
    slug: "saint-marin",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_San_Marino.svg/20px-Flag_of_San_Marino.svg.png",
    prefix: 378,
  },
  {
    iso: "PM",
    name: "Saint Pierre et Miquelon",
    pre: "à",
    slug: "saint-pierre-et-miquelon",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/20px-Flag_of_France.svg.png",
    prefix: 508,
  },
  {
    iso: "VA",
    name: "Vatican",
    pre: "au",
    slug: "vatican",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_the_Vatican_City.svg/18px-Flag_of_the_Vatican_City.svg.png",
    prefix: 379,
  },
  {
    iso: "VC",
    name: "Saint Vincent et les Grenadines",
    pre: "à",
    slug: "saint-vincent-et-les-grenadines",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg/20px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png",
    prefix: 1784,
  },
  { iso: "SH", name: "Sainte Hélène", pre: "à", slug: "sainte-helene" },
  {
    iso: "LC",
    name: "Sainte Lucie",
    pre: "à",
    slug: "sainte-lucie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Saint_Lucia.svg/20px-Flag_of_Saint_Lucia.svg.png",
    prefix: 1758,
  },
  {
    iso: "SB",
    name: "Îles Salomon",
    pre: "aux",
    slug: "iles-salomon",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Solomon_Islands.svg/20px-Flag_of_the_Solomon_Islands.svg.png",
    prefix: 677,
  },
  {
    iso: "WS",
    name: "Samoa",
    pre: "aux",
    slug: "samoa",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/20px-Flag_of_Samoa.svg.png",
    prefix: 685,
  },
  {
    iso: "AS",
    name: "Samoa Americaines",
    pre: "aux",
    slug: "samoa-americaines",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/8/87/Flag_of_American_Samoa.svg/20px-Flag_of_American_Samoa.svg.png",
    prefix: 1684,
  },
  {
    iso: "ST",
    name: "Sao Tome et Principe",
    pre: "à",
    slug: "sao-tome-et-principe",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Sao_Tome_and_Principe.svg/20px-Flag_of_Sao_Tome_and_Principe.svg.png",
    prefix: 239,
  },
  { iso: "S1", name: "Sardaigne", pre: "en", slug: "sardaigne" },
  {
    iso: "SN",
    name: "Sénégal",
    pre: "au",
    slug: "senegal",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/20px-Flag_of_Senegal.svg.png",
    prefix: 221,
  },
  {
    iso: "RS",
    name: "Serbie",
    pre: "en",
    slug: "serbie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/20px-Flag_of_Serbia.svg.png",
    prefix: 381,
  },
  {
    iso: "SC",
    name: "Seychelles",
    pre: "aux",
    slug: "seychelles",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/20px-Flag_of_Seychelles.svg.png",
    prefix: 248,
  },
  { iso: "S2", name: "Sicile", pre: "en", slug: "sicile" },
  {
    iso: "SL",
    name: "Sierra Leone",
    pre: "au",
    slug: "sierra-leone",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/20px-Flag_of_Sierra_Leone.svg.png",
    prefix: 232,
  },
  {
    iso: "SG",
    name: "Singapour",
    pre: "à",
    slug: "singapour",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/20px-Flag_of_Singapore.svg.png",
    prefix: 65,
  },
  {
    iso: "SK",
    name: "Slovaquie",
    pre: "en",
    slug: "slovaquie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/20px-Flag_of_Slovakia.svg.png",
    prefix: 421,
  },
  {
    iso: "SI",
    name: "Slovénie",
    pre: "en",
    slug: "slovenie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/20px-Flag_of_Slovenia.svg.png",
    prefix: 386,
  },
  {
    iso: "SO",
    name: "Somalie",
    pre: "en",
    slug: "somalie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/20px-Flag_of_Somalia.svg.png",
    prefix: 252,
  },
  {
    iso: "SD",
    name: "Soudan",
    pre: "au",
    slug: "soudan",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/20px-Flag_of_Sudan.svg.png",
    prefix: 249,
  },
  {
    iso: "SS",
    name: "Soudan du Sud",
    pre: "au",
    slug: "soudan-du-sud",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Flag_of_South_Sudan.svg/20px-Flag_of_South_Sudan.svg.png",
    prefix: 211,
  },
  {
    iso: "LK",
    name: "Sri Lanka",
    pre: "au",
    slug: "sri-lanka",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/20px-Flag_of_Sri_Lanka.svg.png",
    prefix: 94,
  },
  {
    iso: "BQ",
    name: "Saint Eustache et Saba",
    pre: "à",
    slug: "saint-eustache-et-saba",
  },
  {
    iso: "SX",
    name: "Saint Martin (Pays Bas)",
    pre: "à",
    slug: "saint-martin-pays-bas",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Sint_Maarten.svg/20px-Flag_of_Sint_Maarten.svg.png",
    prefix: 1721,
  },
  {
    iso: "SE",
    name: "Suède",
    pre: "en",
    slug: "suede",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/20px-Flag_of_Sweden.svg.png",
    prefix: 46,
  },
  {
    iso: "CH",
    name: "Suisse",
    pre: "en",
    slug: "suisse",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/15px-Flag_of_Switzerland.svg.png",
    prefix: 41,
  },
  {
    iso: "SR",
    name: "Suriname",
    pre: "au",
    slug: "suriname",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Suriname.svg/20px-Flag_of_Suriname.svg.png",
    prefix: 597,
  },
  {
    iso: "SJ",
    name: "Svalbard et Île Jan Mayen",
    pre: "à",
    slug: "svalbard-et-ile-jan-mayen",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/20px-Flag_of_Norway.svg.png",
    prefix: 47,
  },
  {
    iso: "SZ",
    name: "Swaziland",
    pre: "au",
    slug: "swaziland",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/20px-Flag_of_Eswatini.svg.png",
    prefix: 268,
  },
  {
    iso: "SY",
    name: "Syrie",
    pre: "en",
    slug: "syrie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/20px-Flag_of_Syria.svg.png",
    prefix: 963,
  },
  {
    iso: "TJ",
    name: "Tadjikistan",
    pre: "au",
    slug: "tadjikistan",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/20px-Flag_of_Tajikistan.svg.png",
    prefix: 992,
  },
  {
    iso: "TW",
    name: "Taïwan",
    pre: "à",
    slug: "taiwan",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/20px-Flag_of_the_Republic_of_China.svg.png",
    prefix: 886,
  },
  {
    iso: "TZ",
    name: "Tanzanie",
    pre: "en",
    slug: "tanzanie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/20px-Flag_of_Tanzania.svg.png",
    prefix: 255,
  },
  {
    iso: "TD",
    name: "Tchad",
    pre: "au",
    slug: "tchad",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/20px-Flag_of_Chad.svg.png",
    prefix: 235,
  },
  {
    iso: "CZ",
    name: "République Tchèque",
    pre: "en",
    slug: "republique-tcheque",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/20px-Flag_of_the_Czech_Republic.svg.png",
    prefix: 420,
  },
  {
    iso: "TF",
    name: "Terres Australes Françaises",
    pre: "aux",
    slug: "terres-australes-francaises",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Flag_of_the_French_Southern_and_Antarctic_Lands.svg/20px-Flag_of_the_French_Southern_and_Antarctic_Lands.svg.png",
    prefix: 262,
  },
  {
    iso: "TH",
    name: "Thaïlande",
    pre: "en",
    slug: "thailande",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/20px-Flag_of_Thailand.svg.png",
    prefix: 66,
  },
  { iso: "T1", name: "Tibet", pre: "au", slug: "tibet" },
  {
    iso: "TL",
    name: "Timor Leste",
    pre: "au",
    slug: "timor-leste",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/20px-Flag_of_East_Timor.svg.png",
    prefix: 670,
  },
  {
    iso: "TG",
    name: "Togo",
    pre: "au",
    slug: "togo",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/20px-Flag_of_Togo.svg.png",
    prefix: 228,
  },
  {
    iso: "TK",
    name: "Tokelau",
    pre: "à",
    slug: "tokelau",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Flag_of_Tokelau.svg/20px-Flag_of_Tokelau.svg.png",
    prefix: 690,
  },
  {
    iso: "TO",
    name: "Tonga",
    pre: "aux",
    slug: "tonga",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/20px-Flag_of_Tonga.svg.png",
    prefix: 676,
  },
  {
    iso: "TT",
    name: "Trinité et Tobago",
    pre: "à",
    slug: "trinite-et-tobago",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/20px-Flag_of_Trinidad_and_Tobago.svg.png",
    prefix: 1868,
  },
  {
    iso: "TN",
    name: "Tunisie",
    pre: "en",
    slug: "tunisie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/20px-Flag_of_Tunisia.svg.png",
    prefix: 216,
  },
  {
    iso: "TM",
    name: "Turkmenistan",
    pre: "au",
    slug: "turkmenistan",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/20px-Flag_of_Turkmenistan.svg.png",
    prefix: 993,
  },
  {
    iso: "TC",
    name: "Turks et Caïques",
    pre: "à",
    slug: "turks-et-caiques",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg/20px-Flag_of_the_Turks_and_Caicos_Islands.svg.png",
    prefix: 1649,
  },
  {
    iso: "TR",
    name: "Turquie",
    pre: "en",
    slug: "turquie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/20px-Flag_of_Turkey.svg.png",
    prefix: 90,
  },
  {
    iso: "TV",
    name: "Tuvalu",
    pre: "à",
    slug: "tuvalu",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tuvalu.svg/20px-Flag_of_Tuvalu.svg.png",
    prefix: 688,
  },
  {
    iso: "UA",
    name: "Ukraine",
    pre: "en",
    slug: "ukraine",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/20px-Flag_of_Ukraine.svg.png",
    prefix: 380,
  },
  {
    iso: "UY",
    name: "Uruguay",
    pre: "en",
    slug: "uruguay",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/20px-Flag_of_Uruguay.svg.png",
    prefix: 598,
  },
  {
    iso: "VU",
    name: "Vanuatu",
    pre: "à",
    slug: "vanuatu",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/20px-Flag_of_Vanuatu.svg.png",
    prefix: 678,
  },
  {
    iso: "VE",
    name: "Venezuela",
    pre: "au",
    slug: "venezuela",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/20px-Flag_of_Venezuela.svg.png",
    prefix: 58,
  },
  {
    iso: "VN",
    name: "Vietnam",
    pre: "au",
    slug: "vietnam",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/20px-Flag_of_Vietnam.svg.png",
    prefix: 84,
  },
  {
    iso: "WF",
    name: "Wallis et Futuna",
    pre: "à",
    slug: "wallis-et-futuna",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Flag_of_Wallis_and_Futuna.svg/20px-Flag_of_Wallis_and_Futuna.svg.png",
    prefix: 681,
  },
  {
    iso: "YE",
    name: "Yémen",
    pre: "au",
    slug: "yemen",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Yemen.svg/20px-Flag_of_Yemen.svg.png",
    prefix: 967,
  },
  {
    iso: "ZM",
    name: "Zambie",
    pre: "en",
    slug: "zambie",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/20px-Flag_of_Zambia.svg.png",
    prefix: 260,
  },
  {
    iso: "ZW",
    name: "Zimbabwe",
    pre: "au",
    slug: "zimbabwe",
    flag: "upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/20px-Flag_of_Zimbabwe.svg.png",
    prefix: 263,
  },
];

export default pays;
